volumes:
  db_data:


services:
  nuxt:
    build:
      context: .
      dockerfile: docker/nuxt.Dockerfile
    image: azizramdan/remindme-nuxt
    restart: always
    user: node
    ports:
      - "3010:3000"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    image: azizramdan/remindme-api
    restart: always
    depends_on:
      - mysql
    environment:
      - CONTAINER_ROLE=api

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    image: azizramdan/remindme-nginx
    restart: always
    depends_on:
      - api
    ports:
      - "8010:80"

  mysql:
    image: mysql:8.2
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=remindme
