name: Build docker container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  tests:
    uses: ./.github/workflows/run-test.yml

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3

      - name: Build all images
        run: docker compose build

      - name: Run all service
        run: docker compose up -d --wait

      - name: Run test api service
        run: docker compose run --rm api php artisan test
