name: Run tests

on:
  push:
  workflow_call:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, exif
          coverage: none

      - name: Run composer install
        working-directory: ./src
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        working-directory: ./src
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        working-directory: ./src
        run: php artisan test
